# Generated by Django 4.1.1 on 2023-01-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_newpost_likes_number_user_followers_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
